# NumPy Genel Tekrar

## Bu bölümde okulda bölüm içi seçmeli ders olarak aldığım Veri Bilimi için Python dersinin NumPy konusunu tekrar edeceğim.

In [2]:
# NumPy kütüphanesini np kısaltması ile dahil etmek
import numpy as np 

In [4]:
a = np.array([1,9,7,4])
b = np.array([2,7,6,5])

In [5]:
a*b

array([ 2, 63, 42, 20])

In [6]:
# Eğer numpy olmasaydı:
a = [1,9,7,4]
b = [2,7,6,5]

ab = []

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 63, 42, 20]

In [9]:
a = np.array([1,9,7,4])
b = np.array([2,7,6,5])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [12]:
# sıfırlardan oluşan on elemanlı iki boyutlu array oluşturma
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# birlerden oluşan array
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [16]:
# sıfırdan 31'e kadar (31 hariç) 3'er 3êr sıralı iki boyutlu array
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [17]:
# sıfırdan 1'e kadar eşit aralıkta 10 sayıdan oluşan iki boyutlu array
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
# ortalaması 10, standart sapması 4 olan 3'e 4'lük iki boyutlu array
np.random.normal(10, 4, (3,4))

array([[ 8.36263216, 11.62556181, 14.01478622,  7.45887384],
       [13.92617573,  8.13721974, 10.32455082,  8.27336716],
       [12.27961732,  8.20013294, 17.10774331, 15.38250344]])

In [21]:
# 0 dan 9a kadar olan integerlarla rastgele array
np.random.randint(0,10, (3,3))

array([[7, 4, 4],
       [5, 6, 3],
       [1, 3, 6]])


* **ndim**: _boyut sayısı_
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [22]:
import numpy as np

In [23]:
a = np.random.randint(10, size = 10)

In [24]:
a.ndim

1

In [25]:
a.shape

(10,)

In [26]:
a.size

10

In [27]:
a.dtype

dtype('int32')

In [133]:
b = np.random.randint(10, size = (3,5))
b

array([[7, 4, 4, 8, 7],
       [1, 9, 3, 9, 9],
       [5, 3, 8, 3, 1]])

In [30]:
b.ndim

2

In [31]:
b.shape

(3, 5)

In [32]:
b.size

15

In [33]:
b.dtype

dtype('int32')

## NumPy'da yeniden şekillendirme

In [34]:
import numpy as np

In [37]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a.ndim

1

In [41]:
b = a.reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
b.ndim

2

## Array Birlestirme (Concatenation)

In [43]:
import numpy as np

In [44]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [45]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [46]:
z = np.array([7,8,9])

In [47]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [49]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [51]:
import numpy as np

In [52]:
x = np.array([1,2,3,99,99,3,2,1])

In [53]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [54]:
a,b,c = np.split(x, [3,5])

In [55]:
a

array([1, 2, 3])

In [56]:
b

array([99, 99])

In [57]:
c

array([3, 2, 1])

In [58]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
ust, alt = np.vsplit(m, [2])

In [61]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [65]:
sag, sol = np.hsplit(m, [2])

In [66]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [67]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [68]:
import numpy as np

In [69]:
v = np.array([2,1,4,3,5])

In [70]:
v

array([2, 1, 4, 3, 5])

In [71]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [72]:
v.sort()

In [73]:
v

array([1, 2, 3, 4, 5])

In [74]:
m = np.random.normal(20,5, (3,3))

In [75]:
m

array([[18.68195245, 22.90808314, 17.69652625],
       [18.5679282 , 20.18916773, 19.28825683],
       [10.54408171, 17.93748673, 20.83834172]])

In [76]:
np.sort(m, axis = 1)

array([[17.69652625, 18.68195245, 22.90808314],
       [18.5679282 , 19.28825683, 20.18916773],
       [10.54408171, 17.93748673, 20.83834172]])

In [77]:
np.sort(m, axis = 0)

array([[10.54408171, 17.93748673, 17.69652625],
       [18.5679282 , 20.18916773, 19.28825683],
       [18.68195245, 22.90808314, 20.83834172]])

## Index ile Elemanlara Erişmek

In [78]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([4, 5, 9, 1, 4, 3, 2, 9, 0, 8])

In [79]:
a[0]

4

In [80]:
a[-1]

8

In [81]:
a[0] = 100
a

array([100,   5,   9,   1,   4,   3,   2,   9,   0,   8])

In [82]:
m = np.random.randint(10, size = (3,5))
m

array([[8, 8, 5, 1, 9],
       [8, 3, 3, 5, 6],
       [6, 1, 9, 4, 7]])

In [83]:
m[0,0]

8

In [84]:
m[1,1]

3

In [85]:
m[1, 4]

6

In [86]:
m[1, 4] = 99

In [87]:
m

array([[ 8,  8,  5,  1,  9],
       [ 8,  3,  3,  5, 99],
       [ 6,  1,  9,  4,  7]])

In [88]:
m[1,4] = 2.2
m

array([[8, 8, 5, 1, 9],
       [8, 3, 3, 5, 2],
       [6, 1, 9, 4, 7]])

## Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [89]:
import numpy as np

In [90]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [91]:
a[0:3]

array([20, 21, 22])

In [92]:
a[:3]

array([20, 21, 22])

In [93]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [94]:
a[1::2]

array([21, 23, 25, 27, 29])

In [95]:
a[0::2]

array([20, 22, 24, 26, 28])

In [96]:
a[2::2]

array([22, 24, 26, 28])

In [97]:
a[0::3]

array([20, 23, 26, 29])

In [99]:
m = np.random.randint(10, size = (5,5))
m

array([[8, 3, 2, 9, 8],
       [7, 5, 1, 1, 5],
       [0, 1, 1, 2, 6],
       [2, 8, 5, 5, 5],
       [6, 5, 3, 8, 2]])

In [100]:
m[:,0]

array([8, 7, 0, 2, 6])

In [101]:
m[:,1]

array([3, 5, 1, 8, 5])

In [102]:
m[:,4]

array([8, 5, 6, 5, 2])

In [103]:
m

array([[8, 3, 2, 9, 8],
       [7, 5, 1, 1, 5],
       [0, 1, 1, 2, 6],
       [2, 8, 5, 5, 5],
       [6, 5, 3, 8, 2]])

In [104]:
m[0,:]

array([8, 3, 2, 9, 8])

In [105]:
m[0]

array([8, 3, 2, 9, 8])

In [106]:
m[1,:]

array([7, 5, 1, 1, 5])

In [107]:
m[0:2, 0:3]

array([[8, 3, 2],
       [7, 5, 1]])

In [111]:
m[:,0:2]

array([[8, 3],
       [7, 5],
       [0, 1],
       [2, 8],
       [6, 5]])

In [109]:
m

array([[8, 3, 2, 9, 8],
       [7, 5, 1, 1, 5],
       [0, 1, 1, 2, 6],
       [2, 8, 5, 5, 5],
       [6, 5, 3, 8, 2]])

In [110]:
m[1:3, 0:2]

array([[7, 5],
       [0, 1]])

## Alt Küme Üzerinde İşlem Yapmak

In [112]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[6, 1, 6, 0, 0],
       [9, 1, 1, 4, 1],
       [8, 3, 0, 4, 1],
       [3, 7, 3, 9, 1],
       [1, 6, 5, 7, 4]])

In [113]:
alt_a = a[0:3, 0:2]
alt_a

array([[6, 1],
       [9, 1],
       [8, 3]])

In [114]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [115]:
alt_a

array([[99999,     1],
       [    9,   888],
       [    8,     3]])

In [116]:
a

array([[99999,     1,     6,     0,     0],
       [    9,   888,     1,     4,     1],
       [    8,     3,     0,     4,     1],
       [    3,     7,     3,     9,     1],
       [    1,     6,     5,     7,     4]])

In [117]:
m = np.random.randint(10, size = (5, 5))
m

array([[7, 9, 8, 6, 3],
       [4, 3, 4, 7, 2],
       [6, 6, 2, 1, 7],
       [8, 9, 8, 6, 7],
       [6, 9, 0, 0, 0]])

In [118]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[7, 9],
       [4, 3],
       [6, 6]])

In [119]:
alt_b[0,0] = 9999

In [120]:
alt_b

array([[9999,    9],
       [   4,    3],
       [   6,    6]])

In [121]:
m

array([[7, 9, 8, 6, 3],
       [4, 3, 4, 7, 2],
       [6, 6, 2, 1, 7],
       [8, 9, 8, 6, 7],
       [6, 9, 0, 0, 0]])

## Fancy Index ile Elemanlara Erişmek

In [122]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [123]:
v[1]

3

In [124]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [125]:
al_getir = [1,3,5]

In [126]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [127]:
v[al_getir]

array([ 3,  9, 15])

In [129]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [131]:
m[satir, sutun]

array([1, 5])

In [134]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [135]:
m[0, [1,2]]

array([1, 2])

In [136]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu Eleman İşlemleri

In [139]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [140]:
v < 3

array([ True,  True, False, False, False])

In [141]:
v[v < 3]

array([1, 2])

In [142]:
v[v > 3]

array([4, 5])

In [143]:
v[v != 3]

array([1, 2, 4, 5])

In [144]:
v * 2

array([ 2,  4,  6,  8, 10])

In [145]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [146]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [147]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Matematiksel İşlemler

In [148]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [149]:
v - 1

array([0, 1, 2, 3, 4])

In [150]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [151]:
v * 5

array([ 5, 10, 15, 20, 25])

In [152]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [153]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [154]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [155]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [156]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [157]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

v % 2

In [159]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [160]:
np.absolute(np.array([-3]))

array([3])

In [161]:
np.sin(360)

0.9589157234143065

In [162]:
np.cos(180)

-0.5984600690578581

In [163]:
v = np.array([1,2,3])

In [164]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [165]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [166]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

## NumPy ile İki Bilinmeyenli Denklem Çözümü

In [168]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [169]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [170]:
a

array([[5, 1],
       [1, 3]])

In [171]:
b

array([12, 10])

In [172]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

## BİR SONRAKİ KONUMUZ PANDAS...